name: Codespaces Prebuild

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (root)
        run: npm ci --legacy-peer-deps

      - name: Install Dependencies (identity)
        run: npm --prefix identity ci --legacy-peer-deps

      - name: Install Dependencies (frontend)
        run: npm --prefix frontend ci --legacy-peer-deps

      - name: Prisma Generate
        run: npx prisma generate --schema prisma/schema.prisma

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test -- --run

      - name: Upload Vitest Coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage
          path: coverage
          if-no-files-found: ignore
