name: Require Signed Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  signed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify commit signatures
        uses: mheap/require-signed-commits@v2
        with:
          allow-merge-commits: true

