name: DORA Metrics

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  dora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node scripts/collect-dora.mjs
      - name: Commit metrics
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add metrics/DORA.md metrics/dora.json
            git commit -m "chore(metrics): update DORA [skip ci]"
            git push
          fi

